---
- hosts: lbservers
  tasks:
  - name: Create directory and restart Nginx
    file:
      path: /tmp/logs
      state: directory
    register: created_dir

  - name: Restart Nginx
    become: true
    service:
      name: nginx
      state: restarted
    when: created_dir.changed

